apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sconfigmap
  labels:
    app: k8sconfigmap
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: k8sconfigmap
  template:
    metadata:
      labels:
        app: k8sconfigmap
    spec:
      volumes:
        - name: servicemap-volume
          configMap:
            name: servicemap-config
      containers:
        - name: k8sconfigmap
          image: k8sconfigmap:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: servicemap-volume
              mountPath : "/app/servicemap"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: k8sconfigmap
spec:
  type: NodePort
  selector:
    app: k8sconfigmap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234